### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by arleincho** [kaltura/nginx-vod-module#558] opened 2017-03-13 18:05 UTC
Hi

I using this module from homebrew instalation in my mac and my conf file are attached.
but when i request this url  "clear && curl -i http://127.0.0.1:8005/content/uno.mp4/master.m3u8 -vvv -XPOST -vvvvvvv" the nginx response me 

"* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8005 (#0)
> POST /content/uno.mp4/master.m3u8 HTTP/1.1
> Host: 127.0.0.1:8005
> User-Agent: curl/7.50.3
> Accept: */*
> 
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server"

That I have wrong in my configuration or my server?
are you can help me?

Thanks for you advice.

[vod.conf.zip](https://github.com/kaltura/nginx-vod-module/files/839150/vod.conf.zip)

**Comment by erankor** [comment] 2017-03-13 20:40
The module does not accept POST, only GET/HEAD/OPTIONS. But I don't quite understand why you got 'empty reply from server', it returns error HTTP status 405 when it gets a verb that is not allowed. Did you check the nginx error log?

**Comment by arleincho** [comment] 2017-03-13 20:49
hi.

i dont see nothing in error log.
i see the debug log i send in the log file.
[log.txt](https://github.com/kaltura/nginx-vod-module/files/839575/log.txt)

And i had the same result when i use the GET method.

 clear && curl -i http://127.0.0.1:8005/content/uno.mp -vvv -XGET -vvvvvvv

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8005 (#0)
> GET /content/uno.mp HTTP/1.1
> Host: 127.0.0.1:8005
> User-Agent: curl/7.50.3
> Accept: */*
> 
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server

**Comment by arleincho** [comment] 2017-03-13 20:51
the url i was used is

curl -i http://127.0.0.1:8005/content/uno.mp4/master.m3u8 -vvv 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8005 (#0)
> GET /content/uno.mp4/master.m3u8 HTTP/1.1
> Host: 127.0.0.1:8005
> User-Agent: curl/7.50.3
> Accept: */*
> 
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server

**Comment by erankor** [comment] 2017-03-13 20:59
try moving the error_log directive to global scope (before `server {`) the fact it's inside server may be the cause the error log is incomplete (I think some of the messages are written to a different file)

**Comment by arleincho** [comment] 2017-03-13 21:14
i put the error_log directive outside server, but, i don't see anything new.

i send you the nginx.conf and server configuration.

[Archivo comprimido.zip](https://github.com/kaltura/nginx-vod-module/files/839623/Archivo.comprimido.zip)

maybe the mp4 files is wrong?


the output debug is:

2017/03/13 15:50:58 [debug] 10287#0: *12 rewrite phase: 2
2017/03/13 15:50:58 [debug] 10287#0: *12 post rewrite phase: 3
2017/03/13 15:50:58 [debug] 10287#0: *12 generic phase: 4
2017/03/13 15:50:58 [debug] 10287#0: *12 generic phase: 5
2017/03/13 15:50:58 [debug] 10287#0: *12 access phase: 6
2017/03/13 15:50:58 [debug] 10287#0: *12 access phase: 7
2017/03/13 15:50:58 [debug] 10287#0: *12 post access phase: 8
2017/03/13 15:50:58 [debug] 10287#0: *12 try files phase: 9
2017/03/13 15:50:58 [debug] 10287#0: *12 ngx_http_vod_handler: started
2017/03/13 15:50:58 [debug] 10581#0: kevent set event: 10: ft:-1 fl:0005

but, no happening nothing more.

**Comment by erankor** [comment] 2017-03-13 21:18
I don't follow, the error_log directive in global scope is commented out, and also it points to a different file. Better have just a single error_log directive in global scope and that's it. Without a full error log it's very hard to understand what is going on

**Comment by arleincho** [comment] 2017-03-13 21:25
i have just one error log file now and see the alert:

2017/03/13 16:22:37 [alert] 15203#0: worker process 15205 exited on signal 5

**Comment by erankor** [comment] 2017-03-13 21:39
Try the following - attach gdb to the nginx worker process - gdb -p <process id> (make sure to attach to the worker and not to the master)
Then perform the curl, this will probably crash the process and have gdb report the exception.
At this point type 'bt' in gdb and paste here the resulting stack trace.

Btw, from the log it seems you are using Mac OS X or some other BSD based operating system, this is not an officially supported operated system for this module. But that said, we have folks who use it successfully on OS X, so it is a bit weird that it crashes for you.

**Comment by arleincho** [comment] 2017-03-13 21:49
the output is:

(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007fff8c1d0eca in ?? () from /usr/lib/system/libsystem_kernel.dylib
#1  0x000000010b349789 in ngx_kqueue_process_events ()
#2  0x000000010b3407fc in ngx_process_events_and_timers ()
#3  0x000000010b34846c in ngx_worker_process_cycle ()
#4  0x000000010b346903 in ngx_spawn_process ()
#5  0x000000010b347785 in ngx_master_process_cycle ()
#6  0x000000010b325540 in main ()

**Comment by erankor** [comment] 2017-03-13 22:03
This does not look like the callstack of a crash, it's just the idle stack when nginx is waiting for events. 
I forgot to write you one step - after you run gdb -p <process id> you need to enter 'c' in gdb so that the process will continue running (the process is suspended after gdb attaches to it). Then proceed as I wrote above - run the curl, gdb is expected to report a crash, and type bt

**Comment by arleincho** [comment] 2017-03-13 22:15
the output is:

(gdb) c
Continuing.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007fff675cb075 in ?? ()
(gdb) backtrace
#0  0x00007fff675cb075 in ?? ()
#1  0x00007fff675cdf87 in ?? ()
#2  0x00007fd48af00200 in ?? ()
#3  0x0000000000001982 in ?? ()
#4  0x00007fff50e412a0 in ?? ()
#5  0x00007fff675ce094 in ?? ()
#6  0x00007fd48c800450 in ?? ()
#7  0x00007fd48b829648 in ?? ()
#8  0x00007fff50e41430 in ?? ()
#9  0x00007fff9a19f262 in ?? () from /usr/lib/system/libdyld.dylib
#10 0x0000000000000000 in ?? ()

**Comment by erankor** [comment] 2017-03-14 06:50
For some reason, you don't have symbols, so this isn't really helpful.
Since it crashed for you also when you used POST, and validating the HTTP verb is about the first thing this module does, I think there is something wrong with the way you built it. 
Are you building it dynamically? If so, I suggest you will try to compile it statically to nginx

**Comment by erankor** [comment] 2017-04-09 11:48
@arleincho, can we close this issue?

**Comment by arleincho** [comment] 2017-04-10 15:53
Hi.

in Mac never work, i have tried under linux server and work without problem.

Thanks

**Comment by erankor** [comment] 2017-04-10 20:01
@arleincho, thanks for the update. 
Btw, we have people who use this module on Mac, so probably something wrong with the way you built it / linked against nginx.

**Closed by erankor** 2017-04-10 20:01 UTC
