### ISSUE TITLE
Dash_Encryption_not playing 

### ISSUE THREAD

**Issue by Natarajan92** [kaltura/nginx-vod-module#311] opened 2016-05-26 06:36 UTC
Hi erankor, 

First of all thanks for great s/w. Drm enabled nginx configuration which generates manifest file on the fly is not playing. There is no Default KID value in the generated manifest file and no PSSH data
 
Generated dash manifest file fails mpd validation.

Here is my nginx.conf file: 

#user  nobody;
worker_processes  4;

error_log  /opt/NGINX/error_log;

pid		/var/run/nginx.pid;

events {
	worker_connections  1024;
	multi_accept on;
	use epoll;
}

http {

	ssl_session_cache    shared:SSL:10m;

	upstream kalapi {
		server 192.168.1.59:80;
	}
		
	include	   mime.types;
	default_type  application/octet-stream;

	log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
		'$status $bytes_sent $request_time "$http_referer" "$http_user_agent" "-" - '
		'"$sent_http_x_kaltura" "$http_host" $pid $sent_http_x_kaltura_session - '
		'$request_length "$sent_http_content_range" "$http_x_forwarded_for" '
		'"$http_x_forwarded_server" "$http_x_forwarded_host" "$sent_http_cache_control" '
		'$connection ';

	access_log  /opt/NGINX/access_log main;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	keepalive_timeout 60;
	keepalive_requests 1000;
	client_header_timeout 20;
	client_body_timeout 20;
	reset_timedout_connection on;
	send_timeout 20;

	gzip  on;
	gzip_types application/vnd.apple.mpegurl video/f4m application/dash+xml text/xml;

	# common vod settings
	vod_mode local;
        vod_segment_duration 4000;
        vod_align_segments_to_key_frames on;
        vod_dash_manifest_format segmenttemplate;
        vod_last_modified_types *;
	vod_upstream_location /kalapi;
	vod_upstream_extra_args "pathOnly=1";

	# shared memory zones

	vod_metadata_cache metadata_cache 512m;
	vod_mapping_cache mapping_cache 64m;
	vod_response_cache response_cache 64m;
	vod_performance_counters perf_counters;

	# common file caching / aio

	open_file_cache max=1000 inactive=5m;
	open_file_cache_valid 2m;
	open_file_cache_min_uses 1;
	open_file_cache_errors on;
	aio on;

	server {
		listen 88;
		server_name 192.168.1.59;
		include /etc/nginx/conf.d/kaltura.conf;

	    location /kalapi/ {
            proxy_pass http://kalapi/;
            proxy_set_header Host $http_host;
        }

	
        location /dash/ {
            
	    vod dash;
            vod_drm_request_uri /dash/key.js;
            vod_drm_upstream_location /kalapi;
            vod_drm_enabled on;	   
	    
            root /var/www/html;
	  
            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
      }

	}
	include /etc/nginx/conf.d/ssl.conf;
} 

The key.js file used is 

[{
    "pssh": [{
            "data": "base64 encoded data to be inserted", 
            "uuid": "9a04f079-9840-4286-ab92-e65be0885f95"
        }], 
    "key": "rJ+d6YT1Ks85mV1LFgSjnQ==", 
    "key_id": "n5WBZd+tTei+oUVLnXBnOw=="
}]

Is anything wrong in key.js file or in nginx.conf file.

**Comment by erankor** [comment] 2016-05-26 06:45
nginx-vod does not output the default kid / pssh in the mpd, it is returning them in the init segment.
You should see `ContentProtection` tags in the MPD and a few additional boxes in the init.mp4 (pssh, schi, tenc etc.)
I read at some place that the more recommended / inter-operable way now is indeed to put it on the manifest, but we haven't bumped into any actual issues with the current implementation, so we didn't bother updating it

**Comment by Natarajan92** [comment] 2016-05-26 07:21
Thanks for your reply, So the way of using Nginx.conf file and key.js file is proper ? because the encrypted asset is not playing and key requesting is not going to key server. 

Please find the attached Manifest file generated by Nginx-module
[manifestMPD.zip](https://github.com/kaltura/nginx-vod-module/files/283646/manifestMPD.zip)

**Comment by erankor** [comment] 2016-05-26 07:37
The manifest and json look ok to me, if you don't even see the license request, maybe it's something on the player side. For example we once had a problem where PlayReady would not request the license when the URL was longer than ~400 chars. Another possibility is that it already pulled the license once and cached it (in browser cache / mspr.hds), and in that case the problem may be due to non-matching key / key id (in some cases the bytes of the key id have to be ordered like a GUID)

**Comment by Natarajan92** [comment] 2016-05-26 11:31
Ok, I will check on player side and will come back to you. Is it possible to use same Nginx.conf file for both HLS/Dash conversion ? If so can you provide any sample for it

**Comment by erankor** [comment] 2016-05-26 11:35
There's no problem to use multiple protocols on the same nginx.conf, but you can only have a single protocol per location. We use for example location /hls and location /dash. 
If you want to use a single path for multiple protocols, that can also work with regex locations (e.g. `location ~ .*\.m3u8$` will handle hls) but it's a bit nastier

**Comment by Natarajan92** [comment] 2016-05-30 04:55
If i use MP4Box or Bento4 tool to encrypt, than Dash encrypted asset is playing. It is not playing when i generate MPD with Nginx. For Mp4Box/Bento4/Nginx am using same DRM information(Key). Already i have attached my Config, key.js & manifest file. if you want any other details to find the solution for this problem, i can provide you

**Comment by erankor** [comment] 2016-05-30 06:23
Did you try changing the byte order of the key id provided to nginx-vod ? 
In this case it should be `ZYGVn63f6E2+oUVLnXBnOw==`, generated with:
```
>>> import base64
>>> key_id = 'n5WBZd+tTei+oUVLnXBnOw=='
>>> kid = base64.b64decode(key_id)
>>> kid = kid[3]+kid[2]+kid[1]+kid[0]+kid[5]+kid[4]+kid[7]+kid[6]+kid[8:]
>>> base64.b64encode(kid)
ZYGVn63f6E2+oUVLnXBnOw==
```

If that does not work, please provide:
1. URLs to both MPDs (the one generated by nginx-vod & the one generated by MP4Box)
2. License URL
3. MP4Box command line

**Comment by Natarajan92** [comment] 2016-05-30 10:43
This way of using KID="ZYGVn63f6E2+oUVLnXBnOw==" also not working.
MP4Box command line is, 
For encryption: MP4Box -crypt key.xml video.mp4 -out video-enc.mp4
MP4Box -crypt key.xml audio.mp4 -out audio-enc.mp4
For dash packaging : MP4Box -dash 4000 -rap -frag-rap -sample-groups-traf -profile live -bs-switching no video-enc.mp4 audio-enc.mp4 -out dash.mpd 

Below am attaching the manifest file generated by mp4box and Nginx and the key file used for mp4box encryption

[drm.zip](https://github.com/kaltura/nginx-vod-module/files/289388/drm.zip)

**Comment by Natarajan92** [comment] 2016-05-30 11:45
If i download the manifest file through http request and by manually by adding these information to the manifest file 

<ContentProtection cenc:default_KID="9f958165-dfad-4de8-bea1-454b9d70673b" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
      
      <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
        <mspr:pro>RgQAAAEAAQA8BDwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwAxADAANwAuADAALgA0ADEALgAxADkANQA6ADgAMAAvAGMAeABwAGwAYQB5AHIAZQBhAGQAeQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AMQAwADcALgAwAC4ANAAxAC4AMQA5ADUAOgA4ADAALwBjAHgAcABsAGEAeQByAGUAYQBkAHkALwByAGkAZwBoAHQAcwBtAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABVAEkAXwBVAFIATAA+ADwARABTAF8ASQBEAD4AQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAUQA9AD0APAAvAEQAUwBfAEkARAA+ADwASwBJAEQAPgBaAFkARwBWAG4ANgAzAGYANgBFADIAKwBvAFUAVgBMAG4AWABCAG4ATwB3AD0APQA8AC8ASwBJAEQAPgA8AEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAIAB4AG0AbABuAHMAPQAiACIAPgA8AEMAbwBuAHQAZQBuAHQAUgBlAGYAPgA4AGYANABjAGMAZQBkAGEALQA5ADUAMgA0AC0ANABiADIAMQAtADkAZAAyAGEALQA4AGMAYgBhADgAZQA3AGIAYQA2ADEAZgA8AC8AQwBvAG4AdABlAG4AdABSAGUAZgA+ADwALwBDAFUAUwBUAE8ATQBBAFQAVABSAEkAQgBVAFQARQBTAD4APABDAEgARQBDAEsAUwBVAE0APgB1AEUAbQB3ACsAeAA2AEUAUQBoADQAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</mspr:pro>
      </ContentProtection>


under each Adaptation tag, first segment alone is playing(i.e., 4sec as i have given segment duration as 4000) and am getting key request in server log too.

**Comment by Natarajan92** [comment] 2016-05-30 15:10
Hi Erankor, 

The device that we are using is expecting KID and MSPR pro element in manifest file for playback of encrypted asset. Is there a way to add those in MPD file ?

**Comment by erankor** [comment] 2016-05-30 18:19
I can add it, 2 questions:
1. The Mp4box MPD that you attached had only default_KID, it didn't have mspr:pro, is this manifest working ? I want to understand what is the minimum required to make this work - do we need both mspr:pro tag with the pssh under the `9a04f079-9840-4286-ab92-e65be0885f95` ContentProtection, and a  `cenc:default_KID` attribute on the `urn:mpeg:dash:mp4protection:2011` ContentProtection ?
2. Which device are you testing on ?

**Comment by Natarajan92** [comment] 2016-05-31 06:18
Actually i have downloaded the manifest file by wget command (servername:88/location/path to mp4/manifest.mpd) and added KID and mspr:pro element in it, than loaded manifest file to the player without using nginx module (i.e., http://ip-address/location of downloaded manifest file). once loaded first encrypted segment alone played and play back stopped after 4sec.  

As like above process if we add only KID to the downloaded manifest, than that first encrypted segment itself not played. So, when we use nginx module, the device is expecting for both KID and mspr:pro it seems. 

The Mp4Box MPD [Live profile not live streaming] which has only default KID played 

Am using IP-Set-Top-Box

**Comment by erankor** [comment] 2016-05-31 06:34
Try playing a single bitrate at a time, maybe the problem is not related to DRM now but either to one of the bitrates or to the transition between them. For example, we saw problems when mixing high/main profile h264 with baseline profile. You can pass, for example, manifest-f1.mpd to nginx-vod instead of manifest.mpd to get only the first file.
Regarding mspr.pro, I see that MP4Box does not even include a ContentProtection tag for PlayReady, it only returns a single generic one for cenc, maybe that's why mspr:pro is required only with nginx-vod.

**Comment by Natarajan92** [comment] 2016-05-31 06:48
Tried playing single profile also, not playing. Example-Url used for playback is http://ip-address:88/dash/dashtest-700k.mp4/manifest.mpd.

**Comment by erankor** [comment] 2016-05-31 07:05
If you disable DRM in nginx.conf does it play ?

**Comment by Natarajan92** [comment] 2016-05-31 07:07
yes! clear files are playing

**Comment by erankor** [comment] 2016-05-31 07:11
Hmm... just remembered that `vod_drm_clear_lead_segment_count` is by default 1, so the fact the first segment plays doesn't mean anything :(
Anyway, I need all relevant URLs (so that I'll have the whole stream, not just the MPD) - 
1. nginx-vod manifest (with your manual addition of play ready stuff)
2. mp4box manifest
3. license acquisition url
You can email it to me if you prefer - eran.kornblau at kaltura dot com

**Comment by erankor** [comment] 2016-05-31 07:15
also, another idea, although a long-shot - try removing `<ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"/>` from the nginx-vod manifest, to make it more like the mp4box manifest

**Comment by Natarajan92** [comment] 2016-05-31 07:17
Ok!

**Comment by Natarajan92** [comment] 2016-05-31 07:35
[dash.mpd.zip](https://github.com/kaltura/nginx-vod-module/files/290513/dash.mpd.zip)
As per your idea, changed the manifest file and tried. It doesn't play. :-(

**Comment by erankor** [comment] 2016-05-31 07:38
I meant with the default kid attribute, to make it exactly the same as Mp4Box (as far as DRM is concerned...)

**Comment by Natarajan92** [comment] 2016-05-31 08:38
Not playing

**Comment by erankor** [comment] 2016-05-31 08:45
Ok, so please send me the info that I requested above

**Comment by Natarajan92** [comment] 2016-05-31 08:46
Ok! will mail you the information

**Comment by Natarajan92** [comment] 2016-05-31 12:02
I mailed information to this mail-id "eran.kornblau@kaltura.com"

**Comment by erankor** [comment] 2016-05-31 12:24
Thanks, I gave it a short look (will look more a bit later) and thought of 3 more things that are worth testing:
1. Remove the Widevine pssh from the JSON you supply nginx-vod
2. Disable clear lead in nginx vod (`vod_drm_clear_lead_segment_count 0`)
3. In the manually edited MPD (the one in which you left a single ContentProtection header for cenc with a default_KID attribute) bring the ContentProtection up one level so that it's under AdaptationSet instead of Representation

These will bring nginx-vod's response closer to mp4box, hopefully one of them will do the trick...

**Comment by Natarajan92** [comment] 2016-06-01 08:59
Hi Eran,

Thanks for your thought, The problem is because of Default clear lead segment in nginx vod configuration file. Now it is working. Thank you 

Is it possible to use different key to encrypt different asset ?

**Comment by erankor** [comment] 2016-06-01 15:43
Great, so is there a need to change the manifest ? assuming we want to continue sending a ContentProtection tag per DRM system, we need to add the default_KID / mspr:pro for PlayReady?

The module requests a JSON for each MP4, so you can encrypt different bitrates with different keys on the same manifest. However, not all devices/DRM systems support that (IIRC, Chrome/Widevine worked, but Edge/PlayReady did not), so IMHO it's better to use a single key per MPD.

**Comment by Natarajan92** [comment] 2016-06-01 17:46
As it is working without adding kid/mspr there is no need to change manifest file .  

And my question is , is it possible to use different key for different asset. I.e., each manifest having different key. Am not saying about different keys in single manifest file. 


For eg : Am having 10 movies in mp4 format, each movie with 3 profiles. So totally 30mp4 files. I need to use one key for 1 movie(3mp4files)  so 10keys for 10 movies. I think you may get my question now. Is it possible ? If so than how ?

**Comment by Natarajan92** [comment] 2016-06-01 17:52
As it is working without adding kid/mspr there is no need to change manifest file .  

And my question is , is it possible to use different key for different asset. I.e., each manifest having different key. Am not saying about different keys in single manifest file. 


For eg : Am having 10 movies in mp4 format, each movie with 3 profiles. So totally 30mp4 files. I need to use one key for 1 movie(3mp4files)  so 10keys for 10 movies. I think you may get my question now. Is it possible ? If so than how ?

**Comment by Natarajan92** [comment] 2016-06-01 17:59
To be crisp clear,  am requesting a manifest file like this http://119.82.113.58:88/dash/dashtest-,700,1200,2000,198,k.mp4.urlset/manifest.mpd  it will provide me a encrypted file with one key .. key information are fetched from json file . . 

If i request for different assets like this 



http://119.82.113.58:88/dash/video-,700,1200,2000,198,k.mp4.urlset/manifest.mpd 

or 

http://119.82.113.58:88/dash/test-1700,3000,4400,198,k.mp4.urlset/manifest.mpd 

It is encrypting all with same json file.. i need to use different json file for different request

**Comment by erankor** [comment] 2016-06-01 20:15
You just need to change `vod_drm_request_uri` to something that is dependent on the specific video, and return different jsons for different videos. This parameter supports nginx variables, so if the video id is the string before the first dash, you can do something like:
```
    location ~ ^/dash/([^\-]+)\-.*

        vod dash;
        vod_drm_request_uri /dash/key-$1.js;
        ...
```
This config captures whatever comes before the dash with a regular expression, and then uses this value in the drm uri (using nginx's builtin $1 variable). So it will ask for `key-video.js` in your first example and `key-test.js` in the second one.

**Comment by Natarajan92** [comment] 2016-06-02 08:46
Ok! Thanks 

If this is the case 

http://119.82.113.58:88/dash/june1/video-,700,1200,2000,198,k.mp4.urlset/manifest.mpd

or

http://119.82.113.58:88/dash/may30/test-1700,3000,4400,198,k.mp4.urlset/manifest.mpd

than how to change the vod_drm_request_uri   ?

i have tried as you said 

   location ~ ^/dash/([^\-]+)\-.*

        vod dash;
        vod_drm_request_uri /dash/key-$1.js;
        ...
  As am using one more folder inside dash folder as june1/may30,  it doesn't fetch the key-video.js or key-test.js file instead it throws error as

2016/06/02 14:08:22 [error] 2100#2100: *1 ngx_child_request_wev_handler: upstream returned a bad status 404 while sending to client, client: 192.168.1.59, server: 192.168.1.59, request: "GET /dash/TVN6068376Dash/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "192.168.1.59:88"
2016/06/02 14:08:22 [error] 2100#2100: *1 open() "/etc/nginx/html/50x.html" failed (2: No such file or directory), client: 192.168.1.59, server: 192.168.1.59, request: "GET /dash/TVN6068376Dash/TVN6068376-,700,1200,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "192.168.1.59:88"

**Comment by erankor** [comment] 2016-06-02 10:30
The sample I gave you will try to fetch june1/key-video.js, if you don't want the folder on this request, just change the regular expression so that it won't match it.
Anyway, this is no longer related to this module, these are standard nginx features (regular expression locations, variable captures, etc.) you can probably find some tutorials in the Internet. 
At the end, you need to somehow define the JSON uri using whatever combination of nginx variables. We are using `$vod_suburi` as the uri, which basically means that the full uri of the specific MP4 is used, and our upstream DRM server takes care of parsing whatever it needs from it.

**Comment by Natarajan92** [comment] 2016-06-02 11:07
Thank you !  Can i get any documents to know more about this nginx-features (regular expression locations, variable captures, etc.), It might be helpful for me to apply different key for different assets

**Comment by erankor** [comment] 2016-06-02 11:33
If you curl /dash/Dash616587/key-video.js does it return the file ? If not you are probably missing some location that will handle this request (you will probably to make this location `internal`, so that the key will not be publically available).
Anyway, I don't have nginx documents, try googling for it

**Comment by Natarajan92** [comment] 2016-06-02 11:39
Yes! it returns the file but when i request for manifest, it gives error as like this 

2016/06/02 17:00:21 [error] 3880#3880: *2 ngx_http_vod_dash_parse_uri_file_name: unidentified request, client: 192.168.1.59, server: 192.168.1.59, request: "GET /dash/TVN616587Dash/video-,700,1200,2000,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", subrequest: "/kalapi/dash/key-/dash/TVN616587Dash/video-,700,1200,2000,198,3000,k.mp4.urlset/manifest.mpd.js", host: "192.168.1.59:88"
2016/06/02 17:00:21 [error] 3880#3880: *2 ngx_child_request_wev_handler: unexpected, upstream is null, client: 192.168.1.59, server: 192.168.1.59, request: "GET /dash/TVN616587Dash/video-,700,1200,2000,198,3000,k.mp4.urlset/manifest.mpd HTTP/1.1", host: "192.168.1.59:88"


Curl command used is

**Comment by Natarajan92** [comment] 2016-06-03 05:50
As you said making this location internal, the key should not be publicly available right ?

Is the below way of doing it "internal" is proper way ? why am asking is, am able to get key-file downloadable by wget/curl command.  So anyone can get key know 

location ~ /dash/([^\-]+)\-.* {
            
      	    vod dash;
            vod_segment_duration 4000;
            vod_drm_clear_lead_segment_count 0;
	    vod_drm_enabled on;
            vod_drm_upstream_location /kalapi;
	    vod_drm_request_uri /dash/$1.js;
            root /var/www/html;
	    internal;

            add_header Access-Control-Allow-Headers '*';
            add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
            add_header Access-Control-Allow-Origin '*';
            expires 100d;
      }

**Comment by erankor** [comment] 2016-06-07 08:54
If you have the JSONs stored in files (we, for example, do not, we have some server that generates them by loading the keys from a database) you will need 3 separate locations:
1. a location with `vod dash` to serve the stream
2. a location with `proxy_pass` to issue a local HTTP request to get the JSON (the module only supports getting the JSON over HTTP)
3. a location that serves the JSON files

The location in 2 can be protected by marking it as `internal`, the location in 3 can be protected with something like:
```
		allow 127.0.0.1/32;
		deny all;
```

**Comment by erankor** [comment] 2016-06-14 11:17
Hi @Natarajan92, can this be closed ?

**Closed** 2016-06-15 03:51 UTC
