### ISSUE TITLE
PlayReady Mpeg-dash Edge 16 playback no more working

### ISSUE THREAD

**Issue by marzipi** [kaltura/nginx-vod-module#834] opened 2018-04-27 09:43 UTC
Dear Erankor,

I have been using your module with DRM for Widevine, PlayReady  CENC and Fairplay packaging for a long time now and it is working perfectly. Thank you for all!

We have now some problems with PlayReady on windows 10. (edge16) and we are no more able to decode the video. The problem seems to be the same with Wowza DRM module:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14593018/ 

Do you know if your module is affected by this new problem?
Thank you again for your support.
Pierre

**Comment by erankor** [comment] 2018-04-27 11:36
@marzipi, are you using clear lead? (the default is on - see vod_drm_clear_lead_segment_count). If so, try to disable it. 
We have bumped into this issue as well, it seems to be a bug in Edge/PlayReady.
We are tracking this issue here (don't know if it's a duplicate of the issue you referenced) - 
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12658991/
This issue was opened roughly ~9 months ago, it seems MSFT are not in any hurry... :( 
We can only hope the fix arrive during our lifetime...

**Comment by marzipi** [comment] 2018-04-27 12:08
Hi Erankor,
It works again by disabling clear lead ... thank you very much for your help!
Pierre

**Comment by marzipi** [comment] 2018-04-27 15:07
Hi Erankor,
Microsoft have just solved the problem  and  the patch is included in
https://support.microsoft.com/en-us/help/4093105/windows-10-update-kb4093105.
Clear lead works again with these new fixes ...
Thank you again
Pierre

**Comment by erankor** [comment] 2018-04-27 15:29
Wow! you probably have some good friends in Microsoft :)
Thanks for the update!

**Closed** 2018-04-27 15:30 UTC
