### ISSUE TITLE
Using mapped mode to request playlist json from another server response 502 Bad Gateway

### ISSUE THREAD

**Issue by sywtw** [kaltura/nginx-vod-module#828] opened 2018-04-23 09:36 UTC
After install nginx and nginx-vod-module followed by https://github.com/kaltura/nginx-vod-module/issues/741 instructions.

Add the following config in `http` block

    upstream foobar {
        server 172.17.0.1:8000;
    }

Add the following config in `server` block

    location ^~ /foobar/ {
        proxy_pass http://foobar/;
        proxy_set_header Host $http_host;
    }

Add the following directives after `vod hls` directive in hls `location` block

    vod_mode mapped;
    vod_upstream_location /foobar;

Request http://172.17.0.1:8000/hls/playlist.json, response as below

    {
	"durations": [ 172000, 171000 ],
	"sequences": [
		{
			"clips": [
				{
					"type": "source",
					"path": "/usr/local/nginx/html/063f3827-c8f8-4334-b346-3e8fee9cd7ed.mp4"
				},
				{
					"type": "source",
					"path": "/usr/local/nginx/html/0f645ca9-7bd8-40b9-bc45-83de9b07e10e.mp4"
				}
			]
		}
	]
    }

But request http://172.17.0.2/hls/playlist.json/index.m3u8, response 502 Bad Gateway, not m3u8

Any step wrong? And how to fix it?

**Comment by erankor** [comment] 2018-04-24 06:17
Did you check the error log?

**Comment by sywtw** [comment] 2018-04-24 06:35
Log from `error.log`. Do you recognize issue?

    2018/04/24 06:30:13 [error] 32#32: *6 ngx_child_request_wev_handler: upstream connection was closed with 655 bytes left to read while sending to client, client: 172.17.0.1, server: , request: "GET /hls/playlist.json/index.m3u8 HTTP/1.1", host: "172.17.0.2"
    2018/04/24 06:30:13 [error] 32#32: *6 ngx_child_request_wev_handler: upstream connection was closed with 655 bytes left to read while sending to client, client: 172.17.0.1, server: , request: "GET /hls/playlist.json/index.m3u8 HTTP/1.1", host: "172.17.0.2"
    2018/04/24 06:30:13 [error] 32#32: *6 ngx_child_request_wev_handler: upstream connection was closed with 655 bytes left to read while sending to client, client: 172.17.0.1, server: , request: "GET /hls/playlist.json/index.m3u8 HTTP/1.1", host: "172.17.0.2"

**Comment by erankor** [comment] 2018-04-24 06:37
Which version of nginx are you using? If >= 1.13, this may be the same as https://github.com/kaltura/nginx-vod-module/issues/819

**Comment by sywtw** [comment] 2018-04-24 06:44
On nginx-1.14.0 and nginx-1.12.2, got the same response.

**Comment by erankor** [comment] 2018-04-24 07:06
Are you saying master.m3u8 consistently works while index.m3u8 consistency fails? It's very weird if that is the case...
What is the upstream server? also nginx? can you check if there are any errors there?

**Comment by sywtw** [comment] 2018-04-24 08:06
master.m3u8 and index.m3u8 consistency fails.

Upstream server is nginx too.

**error.log**

    2018/04/24 08:02:01 [error] 209#209: *11 ngx_child_request_wev_handler: upstream connection was closed with 312 bytes left to read while sending to client, client: 172.17.0.1, server: , request: "GET /hls/playlist.json/index.m3u8 HTTP/1.1", host: "172.17.0.2"
    2018/04/24 08:02:01 [error] 209#209: *11 ngx_child_request_wev_handler: upstream connection was closed with 312 bytes left to read while sending to client, client: 172.17.0.1, server: , request: "GET /hls/playlist.json/index.m3u8 HTTP/1.1", host: "172.17.0.2"
    2018/04/24 08:02:01 [error] 209#209: *11 ngx_child_request_wev_handler: upstream connection was closed with 312 bytes left to read while sending to client, client: 172.17.0.1, server: , request: "GET /hls/playlist.json/index.m3u8 HTTP/1.1", host: "172.17.0.2"

**access.log**

    172.17.0.1 - - [24/Apr/2018:08:02:01 +0000] "GET /hls/playlist.json/index.m3u8 HTTP/1.1" 502 173 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"

**debug.log**

    2018/04/24 08:02:01 [error] 209#209: *11 ngx_child_request_wev_handler: upstream connection was closed with 312 bytes left to read while sending to client, client: 172.17.0.1, server: , request: "GET /hls/playlist.json/index.m3u8 HTTP/1.1", host: "172.17.0.2"

**access.log from upstream server**

    172.17.0.2 - - [24/Apr/2018:08:02:01 +0000] "GET /hls/playlist.json HTTP/1.0" 206 312 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"

**Comment by sywtw** [comment] 2018-04-25 00:52
Okay, I will try, thank you for your suggestion.

**Comment by sywtw** [comment] 2018-04-25 03:58
I compile nginx with debug, and the logs is below, but I still can't recognize the problem from logs.

Could you check the logs for me? Thank you.

[nginx-debug.log](https://github.com/kaltura/nginx-vod-module/files/1945398/nginx-debug.log)
[nginx-upstream.log](https://github.com/kaltura/nginx-vod-module/files/1945399/nginx-upstream.log)

**Comment by erankor** [comment] 2018-04-25 06:12
From a quick look, these are for nginx 1.14.0, as mentioned above there seems to be an issue following some changes in 1.13.x (probably this commit https://github.com/nginx/nginx/commit/7c5c15a25d22b05f1baabfb14395a7924fe4fd8c). 
Please check only with 1.12

**Comment by sywtw** [comment] 2018-04-25 07:09
It's working on nginx 1.12.2 finally.

Maybe I overlook something while test on nginx 1.12.2 in the beginning.

Thank you for your help.

**Comment by erankor** [comment] 2018-04-25 08:35
Thanks for the update. 
I've just pushed https://github.com/kaltura/nginx-vod-module/pull/829 which should resolve this issue for 1.13.10+

**Comment by fsouza** [comment] 2018-04-26 00:04
@erankor I've updated our setup to use nginx@1.14 and vod-module@master and initially got the error ``too big subrequest response``. I set the directive ``subrequest_output_buffer_size`` accordingly then I was able to get the HLS playlist and the DASH manifest. The video starts playing, but eventually it stops playing (around the 3rd segment) and the logs show the workers segfaulting:

```
packager_1    | 2018/04/25 23:57:43 [alert] 1#1: worker process 903 exited on signal 11
packager_1    | 2018/04/25 23:57:44 [alert] 1#1: worker process 936 exited on signal 11
packager_1    | 2018/04/25 23:57:46 [alert] 1#1: worker process 969 exited on signal 11
packager_1    | 2018/04/25 23:57:47 [alert] 1#1: worker process 1002 exited on signal 11
packager_1    | 2018/04/25 23:57:48 [alert] 1#1: worker process 1035 exited on signal 11
packager_1    | 2018/04/25 23:57:50 [alert] 1#1: worker process 1068 exited on signal 11
packager_1    | 2018/04/25 23:57:51 [alert] 1#1: worker process 1101 exited on signal 11
packager_1    | 2018/04/25 23:57:53 [alert] 1#1: worker process 1134 exited on signal 11
packager_1    | 2018/04/25 23:57:58 [alert] 1#1: worker process 1167 exited on signal 11
packager_1    | 2018/04/25 23:57:59 [alert] 1#1: worker process 1200 exited on signal 11
packager_1    | 2018/04/25 23:58:00 [alert] 1#1: worker process 1233 exited on signal 11
packager_1    | 2018/04/25 23:58:06 [alert] 1#1: worker process 1266 exited on signal 11
packager_1    | 2018/04/25 23:58:07 [alert] 1#1: worker process 1299 exited on signal 11
packager_1    | 2018/04/25 23:58:08 [alert] 1#1: worker process 1332 exited on signal 11
```

We're using mapped mode. I'll try to come up with a small reproducer, but let me know if you need any information specifically.

**Comment by jessp01** [comment] 2018-04-26 13:17
Hi @sywtw,

Can you please provide a backtrace?
For this to be meaningful, you'll need to use a Nginx binary [and the VOD SO, if you're loading it dynamically] that includes debug symbols [i.e: not stripped]. 

In your main Nginx conf file, add:
``
daemon  off;
master_process  off;
```

Make sure to stop any running Nginx instances and then run it with GDB, like so:
```
$ gdb --args  /usr/sbin/nginx -c /path/to/your/main/conf
```

In the GDB console, type `r` and hit the return key.
Make your request and when it crushes, type:
```
(gdb) bt full
```

and post the output.

Thanks,

**Comment by fsouza** [comment] 2018-04-26 18:09
@jessp01 sure thing! Recompiled with ``-O0 -g``, we're linking the module statically.

This time it failed right after the first segment. Here's the output:

```
# gdb --args /usr/local/nginx/sbin/nginx
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/nginx/sbin/nginx...done.
(gdb) r
Starting program: /usr/local/nginx/sbin/nginx
[New LWP 29]
[New LWP 30]
[New LWP 31]
[New LWP 32]
[New LWP 33]
[New LWP 34]
[New LWP 35]
[New LWP 36]
[New LWP 37]
[New LWP 38]
[New LWP 39]
[New LWP 40]
[New LWP 41]
[New LWP 42]
[New LWP 43]
[New LWP 44]
[New LWP 45]
[New LWP 46]
[New LWP 47]
[New LWP 48]
[New LWP 49]
[New LWP 50]
[New LWP 51]
[New LWP 52]
[New LWP 53]
[New LWP 54]
[New LWP 55]
[New LWP 56]
[New LWP 57]
[New LWP 58]
[New LWP 59]
[New LWP 60]
2018/04/26 18:07:21 [warn] 25#25: audio_encoder_process_init: failed to get AAC encoder, audio encoding is disabled. recompile libavcodec with libfdk_aac to enable it
172.18.0.1 - - [26/Apr/2018:18:07:24 +0000] "GET /video/hls/2018/02/12/75458_1_Wrights-Widow_wg/index-f1-v1-a1.m3u8 HTTP/1.1" 200 268 "localhost" "http://localhost:9073/video/hls/2018/02/12/75458_1_Wrights-Widow_wg/master.m3u8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15" "-"
172.18.0.1 - - [26/Apr/2018:18:07:24 +0000] "GET /video/hls/2018/02/12/75458_1_Wrights-Widow_wg/segment-2-f2-v1-a1.ts HTTP/1.1" 200 250040 "localhost" "http://localhost:9073/video/hls/2018/02/12/75458_1_Wrights-Widow_wg/master.m3u8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15" "-"

Thread 1 "nginx" received signal SIGSEGV, Segmentation fault.
0x00005555555c54fc in ngx_event_pipe_remove_shadow_links (buf=0x555555a3be40)
    at src/event/ngx_event_pipe.c:1003
1003	src/event/ngx_event_pipe.c: No such file or directory.
(gdb) bt full
#0  0x00005555555c54fc in ngx_event_pipe_remove_shadow_links (
    buf=0x555555a3be40) at src/event/ngx_event_pipe.c:1003
        b = 0x0
        next = 0x0
#1  0x00005555555c3911 in ngx_event_pipe_read_upstream (p=0x555555a3c018)
    at src/event/ngx_event_pipe.c:343
        limit = 93824993164537
        n = 18531
        size = 8
        rc = 140737488349184
        b = 0x555555ae2fa0
        delay = 0
        chain = 0x555555ad01a8
        cl = 0x555555ad01a8
        ln = 0x555555a50020
#2  0x00005555555c2eeb in ngx_event_pipe (p=0x555555a3c018, do_write=0)
    at src/event/ngx_event_pipe.c:49
        rc = 93824992450812
        flags = 93824997736576
        rev = 0x555555a94818
        wev = 0x7fffffffe840
#3  0x0000555555614ca5 in ngx_http_upstream_process_upstream (
    r=0x555555ae2dc0, u=0x555555a3bb08) at src/http/ngx_http_upstream.c:3874
---Type <return> to continue, or q <return> to quit---
        rev = 0x7ffff7e62680
        p = 0x555555a3c018
        c = 0x7fffedf82010
#4  0x00005555556132f9 in ngx_http_upstream_send_response (r=0x555555ae2dc0,
    u=0x555555a3bb08) at src/http/ngx_http_upstream.c:3193
        n = 93824997374728
        rc = 0
        p = 0x555555a3c018
        c = 0x7fffedf813e0
        clcf = 0x555555a00e08
#5  0x00005555556113f1 in ngx_http_upstream_process_header (r=0x555555ae2dc0,
    u=0x555555a3bb08) at src/http/ngx_http_upstream.c:2391
        n = 19503
        rc = 0
        c = 0x7fffedf82010
#6  0x000055555560eec6 in ngx_http_upstream_handler (ev=0x7ffff7e62680)
    at src/http/ngx_http_upstream.c:1280
        c = 0x7fffedf813e0
        r = 0x555555ae2dc0
        u = 0x555555a3bb08
#7  0x00005555555d10a9 in ngx_epoll_process_events (cycle=0x5555559d9af0,
    timer=2750, flags=1) at src/event/modules/ngx_epoll_module.c:902
        events = 1
---Type <return> to continue, or q <return> to quit---
        revents = 5
        instance = 1
        i = 0
        level = 140737488349648
        err = 0
        rev = 0x7ffff7e62680
        wev = 0xabe
        queue = 0x7ffff7e62768
        c = 0x7fffedf82010
#8  0x00005555555bd870 in ngx_process_events_and_timers (cycle=0x5555559d9af0)
    at src/event/ngx_event.c:242
        flags = 1
        timer = 2750
        delta = 132141656
#9  0x00005555555cc9bc in ngx_single_process_cycle (cycle=0x5555559d9af0)
    at src/os/unix/ngx_process_cycle.c:310
        i = 54
#10 0x000055555558575d in main (argc=1, argv=0x7fffffffed68)
    at src/core/nginx.c:379
        b = 0x7fffffffead0
        log = 0x55555595f260 <ngx_log>
        i = 18446744073709551614
        cycle = 0x5555559d9af0
---Type <return> to continue, or q <return> to quit---
        init_cycle = {conf_ctx = 0x0, pool = 0x5555559d9580,
          log = 0x55555595f260 <ngx_log>, new_log = {log_level = 0,
            file = 0x0, connection = 0, disk_full_time = 0, handler = 0x0,
            data = 0x0, writer = 0x0, wdata = 0x0, action = 0x0, next = 0x0},
          log_use_stderr = 0, files = 0x0, free_connections = 0x0,
          free_connection_n = 0, modules = 0x0, modules_n = 0,
          modules_used = 0, reusable_connections_queue = {prev = 0x0,
            next = 0x0}, reusable_connections_n = 0, listening = {elts = 0x0,
            nelts = 0, size = 0, nalloc = 0, pool = 0x0}, paths = {elts = 0x0,
            nelts = 0, size = 0, nalloc = 0, pool = 0x0}, config_dump = {
            elts = 0x0, nelts = 0, size = 0, nalloc = 0, pool = 0x0},
          config_dump_rbtree = {root = 0x0, sentinel = 0x0, insert = 0x0},
          config_dump_sentinel = {key = 0, left = 0x0, right = 0x0,
            parent = 0x0, color = 0 '\000', data = 0 '\000'}, open_files = {
            last = 0x0, part = {elts = 0x0, nelts = 0, next = 0x0}, size = 0,
            nalloc = 0, pool = 0x0}, shared_memory = {last = 0x0, part = {
              elts = 0x0, nelts = 0, next = 0x0}, size = 0, nalloc = 0,
            pool = 0x0}, connection_n = 0, files_n = 0, connections = 0x0,
          read_events = 0x0, write_events = 0x0, old_cycle = 0x0, conf_file = {
            len = 32, data = 0x5555559d95d0 "\002"}, conf_param = {len = 0,
            data = 0x0}, conf_prefix = {len = 22,
            data = 0x5555559d95d0 "\002"}, prefix = {len = 17,
            data = 0x5555556f710e "/usr/local/nginx/"}, lock_file = {len = 0,
---Type <return> to continue, or q <return> to quit---
            data = 0x0}, hostname = {len = 0, data = 0x0}}
        cd = 0x7ffff7d961fc <malloc+941>
        ccf = 0x5555559db660
```

**Comment by fsouza** [comment] 2018-04-29 14:38
@erankor awesome, no segfaults here on #836, thanks for working on that! :)

**Comment by erankor** [comment] 2018-04-29 14:40
Great, merged. 
Thanks for the update!

**Closed by erankor** 2018-04-29 14:40 UTC
