### ISSUE TITLE
Unable to locate files with spaces in the path

### ISSUE THREAD

**Issue by shnhrrsn** [kaltura/nginx-vod-module#61] opened 2015-03-04 03:39 UTC
The module doesn't appear decode the request URI, causing it look on the FS for files with `%20` in the name instead if properly looking for files with a space instead.

**Comment by erankor** [comment] 2015-03-04 05:31
What mode are you using (local/mapped) ? can you send your nginx.conf and URI ? does it work when encoding the space as + ?

**Comment by jessp01** [comment] 2015-03-13 18:08
@shnhrrsn - just pinging.. 
Thanks

**Comment by shnhrrsn** [comment] 2015-03-18 05:49
Sorry for the delay, I'm using local:

```
server {
        listen 8190;

        open_file_cache          max=1000 inactive=5m;
        open_file_cache_valid    2m;
        open_file_cache_min_uses 1;
        open_file_cache_errors   on;

        aio on;

        location ~ ^/media/ {
                vod hls;
                vod_mode local;
                vod_moov_cache moov_cache 512m;

                # Temp workaround
                rewrite ^(.+?)%20(.+?)$ "$1 $2";

                root /data;

                gzip on;
                gzip_types application/vnd.apple.mpegurl;

                expires 100d;
        }
}
```

I'm actually noticing that occasionally when I request the file with spaces (as opposed to %20), nginx 400's almost immediately -- so it looks like the m3u8 file should be encoding spaces to %20 and then handling/decoding %20 back to a space on request.

Encoding the space as a + doesn't work at all.

**Comment by erankor** [comment] 2015-03-18 08:13
Thanks, I'll check it out.
As a workaround, try adding these 2 lines to the media location:
vod_hls_absolute_index_urls off;
vod_hls_absolute_master_urls off;

**Comment by erankor** [comment] 2015-03-18 09:18
@shnhrrsn, even though escaping the URLs in the M3U8 sounds like the right thing to do, I could not reproduce the problem. Few questions:
1. Can you send the file name and URL that doesn't play for you ?
2. On which device does it fail to play - iPhone/iPad ? Mac ? ...
3. Are you using the latest version of the code ?

Here's is what I tried - nginx.conf:
                location ~ ^/local/hls/content/ {
                        vod hls;
                        vod_mode local;

                        add_header X-Me $hostname;
                        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
                        expires 100d;
                }
(btw, no reason to use a regular expression here, you can just use location /media/, I used a regex only to match your configuration)

file name:
/usr/local/nginx/html/local/hls/content/a b.mp4
URL - tried both:
http://lbd.kaltura.com:8001/local/hls/content/a b.mp4/index.m3u8
and:
http://lbd.kaltura.com:8001/local/hls/content/a%20b.mp4/index.m3u8
on my iPhone and both play.

**Comment by erankor** [comment] 2015-04-14 10:27
Didn't get any reply for a month, closing the issue

**Closed by erankor** 2015-04-14 10:27 UTC
