### ISSUE TITLE
I've got an error while building on Ubuntu and ElementaryOS

### ISSUE THREAD

**Issue by watershine** [kaltura/nginx-vod-module#113] opened 2015-06-29 08:27 UTC
I've tried to build nginx with the module without any success.
Nginx 1.8.0 and 1.9.2
gcc 4.8.4

Running travis_build.sh has the same issue.
I tried to follow this as well : https://github.com/kaltura/nginx-vod-module/issues/81 without success.

Here is the output of make : 
```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail -I src/stream \
		-o objs/addon/hls/mp4_to_annexb_filter.o \
		../nginx-vod-module-master/vod/hls/mp4_to_annexb_filter.c
In file included from ../nginx-vod-module-master/vod/hls/../common.h:56:0,
                 from ../nginx-vod-module-master/vod/hls/media_filter.h:5,
                 from ../nginx-vod-module-master/vod/hls/mp4_to_annexb_filter.h:5,
                 from ../nginx-vod-module-master/vod/hls/mp4_to_annexb_filter.c:1:
../nginx-vod-module-master/vod/hls/mp4_to_annexb_filter.c: In function ‘mp4_to_annexb_write’:
src/core/ngx_core.h:100:37: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                     ^
../nginx-vod-module-master/vod/hls/../common.h:65:23: note: in expansion of macro ‘ngx_min’
 #define vod_min(x, y) ngx_min(x, y)
                       ^
../nginx-vod-module-master/vod/hls/mp4_to_annexb_filter.c:179:17: note: in expansion of macro ‘vod_min’
    write_size = vod_min(state->packet_size_left, buffer_end - buffer);
                 ^
src/core/ngx_core.h:100:54: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                                      ^
../nginx-vod-module-master/vod/hls/../common.h:65:23: note: in expansion of macro ‘ngx_min’
 #define vod_min(x, y) ngx_min(x, y)
                       ^
../nginx-vod-module-master/vod/hls/mp4_to_annexb_filter.c:179:17: note: in expansion of macro ‘vod_min’
    write_size = vod_min(state->packet_size_left, buffer_end - buffer);
                 ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/hls/mp4_to_annexb_filter.o] Error 1
make[1]: Leaving directory `/home/kevin/nginx-1.9.2'
make: *** [build] Error 2
```

Any help would be appreciated

Regards,
Kevin

**Comment by erankor** [comment] 2015-06-29 08:34
Did you try removing the 'treat warnings as errors' option, as I suggested on that other thread:

"To remove this option, edit ./objs/Makefile, search for -Werror and remove it, for exmaple, I currently have:
CFLAGS = -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g
so it would be:
CFLAGS = -pipe -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g"

If you do that and you compile, you should get the list of all warnings in your environment (there may be some more warnings on other source files), paste them here and I'll handle them.

**Comment by watershine** [comment] 2015-06-29 09:06
Hi Erankor,

Thank you for your fast response.
Here is the output with the Makefile modified : 

```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g  -I../nginx-rtmp-module-master  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail -I src/stream \
		-o objs/addon/mp4/mp4_encrypt.o \
		../nginx-vod-module-master/vod/mp4/mp4_encrypt.c
In file included from ../nginx-vod-module-master/vod/mp4/../common.h:56:0,
                 from ../nginx-vod-module-master/vod/mp4/../dynamic_buffer.h:5,
                 from ../nginx-vod-module-master/vod/mp4/mp4_encrypt.h:6,
                 from ../nginx-vod-module-master/vod/mp4/mp4_encrypt.c:1:
../nginx-vod-module-master/vod/mp4/mp4_encrypt.c: In function ‘mp4_encrypt_video_write_buffer’:
src/core/ngx_core.h:100:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                     ^
../nginx-vod-module-master/vod/mp4/../common.h:65:23: note: in expansion of macro ‘ngx_min’
 #define vod_min(x, y) ngx_min(x, y)
                       ^
../nginx-vod-module-master/vod/mp4/mp4_encrypt.c:367:17: note: in expansion of macro ‘vod_min’
    write_size = vod_min(state->packet_size_left, buffer_end - cur_pos);
                 ^
src/core/ngx_core.h:100:54: warning: signed and unsigned type in conditional expression [-Wsign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                                      ^
../nginx-vod-module-master/vod/mp4/../common.h:65:23: note: in expansion of macro ‘ngx_min’
 #define vod_min(x, y) ngx_min(x, y)
                       ^
../nginx-vod-module-master/vod/mp4/mp4_encrypt.c:367:17: note: in expansion of macro ‘vod_min’
    write_size = vod_min(state->packet_size_left, buffer_end - cur_pos);
                 ^
../nginx-vod-module-master/vod/mp4/mp4_encrypt.c: In function ‘mp4_encrypt_audio_write_buffer’:
src/core/ngx_core.h:100:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                     ^
../nginx-vod-module-master/vod/mp4/../common.h:65:23: note: in expansion of macro ‘ngx_min’
 #define vod_min(x, y) ngx_min(x, y)
                       ^
../nginx-vod-module-master/vod/mp4/mp4_encrypt.c:567:16: note: in expansion of macro ‘vod_min’
   write_size = vod_min(state->frame_size_left, buffer_end - cur_pos);
                ^
src/core/ngx_core.h:100:54: warning: signed and unsigned type in conditional expression [-Wsign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                                      ^
../nginx-vod-module-master/vod/mp4/../common.h:65:23: note: in expansion of macro ‘ngx_min’
 #define vod_min(x, y) ngx_min(x, y)
                       ^
../nginx-vod-module-master/vod/mp4/mp4_encrypt.c:567:16: note: in expansion of macro ‘vod_min’
   write_size = vod_min(state->frame_size_left, buffer_end - cur_pos);
                ^
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -g  -I../nginx-rtmp-module-master  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail -I src/stream \
		-o objs/addon/mp4/mp4_parser.o \
		../nginx-vod-module-master/vod/mp4/mp4_parser.c
../nginx-vod-module-master/vod/mp4/mp4_parser.c: In function ‘mp4_parser_read_config_descriptor’:
../nginx-vod-module-master/vod/mp4/mp4_parser.c:1381:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (len > stream->end_pos - stream->cur_pos)
```

It goes to the end of make and the rest seems alright.
Do you need more info ?

**Comment by erankor** [comment] 2015-06-29 09:09
That looks fine, I'll merge a fix shortly and will ask you try again without disabling 'warnings as errors'

Thanks

**Comment by erankor** [comment] 2015-06-29 10:23
Please pull the latest master and run ./configure & make again

**Comment by watershine** [comment] 2015-06-29 10:44
Now I have this error : 
```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I../nginx-rtmp-module-master  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail -I src/stream \
		-o objs/addon/vod/read_cache.o \
		../nginx-vod-module-master/vod/read_cache.c
../nginx-vod-module-master/vod/read_cache.c: In function ‘read_cache_get_from_cache’:
../nginx-vod-module-master/vod/read_cache.c:27:13: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   *buffer = (u_char*)offset;
             ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/vod/read_cache.o] Error 1
make[1]: Leaving directory `/home/kevin/nginx-1.9.2'
make: *** [build] Error 2
```

**Comment by erankor** [comment] 2015-06-29 10:49
please try to change this line to:
*buffer = (u_char*)(uintptr_t)offset;

but this is rather weird, any chance you are working on a 32 bit machine ?

**Comment by watershine** [comment] 2015-06-29 10:52
I'm on a 32 bit machine. It's actually running in Virtual Box (my processor doesn't support 64 bit virtualization)

**Comment by erankor** [comment] 2015-06-29 10:55
ok, so now I know why it doesn't work for you while it does for me :)
does that fix it ?

**Comment by erankor** [comment] 2015-06-29 10:56
oops just noticed github removed the asterisk from my comment - it should be u_char <asterisk>.
or in other words, just add the (uintptr_t) part to the original line

**Comment by watershine** [comment] 2015-06-29 11:10
Seems to fix it.
"make install" is good and the module is listed with "nginx -V" command

**Comment by kaltura-hooks** [comment] 2015-06-29 11:34
Hi @watershine,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Is Nginx installed from the kaltura-nginx RPM or deb package?
	When using RPM, paste the output for:
```
	# rpm -qa kaltura-nginx
```	
	For deb based systems:
```	
	# dpkg -l kaltura-nginx
```
 - If the issue is with the install process, please provide full output of the apt-get/yum install command.
 - If you compiled Nginx on your own, please provide the output for:
	```
	$ uname -a

	$ gcc -v
	```
	If using a compiler other than GCC, please provide exact name and version.
	Also, provide the configure line you used.
 - Check Nginx error logs and provide relevant output

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erankor** [comment] 2015-06-29 12:12
great, I will merge that change as well

**Closed by erankor** 2015-06-29 12:12 UTC

**Comment by watershine** [comment] 2015-06-30 01:53
Thank you very much for this fast help.
