### ISSUE TITLE
Unable to play index.m3u8

### ISSUE THREAD

**Issue by mchulet** [kaltura/nginx-vod-module#533] opened 2017-02-19 17:48 UTC
Hi,
  Please excuse as my knowledge is very limited in this space. My problem is that I have setup nginx-vod-module by following instructions from readme on RPi 3 Raspian which is derived from Ubuntu. I have also taken help from response to: https://github.com/kaltura/nginx-vod-module/issues/149

I am using videojs to play from local URL: http://192.168.1.3/content/test.mp4/index.m3u8

Through VLC Player I am able to play this but it does not play in browser through videojs, error I get is:
"No compatible source was found for this media"

Need help to resolve this cause I have tried all that I could in my capacity...

-Thanks

**Comment by erankor** [comment] 2017-02-19 19:31
From your description I would guess the problem is missing CORS headers, check your browser console for errors, you should see a security error if that is the case.
The fix is to add to your conf something like this:
```
add_header 'Access-Control-Allow-Headers' 'Origin,Range,Accept-Encoding,Referer,Cache-Control';
add_header 'Access-Control-Expose-Headers' 'Server,Content-Length,Content-Range,Date';
add_header 'Access-Control-Allow-Methods' 'GET, HEAD, OPTIONS';
add_header 'Access-Control-Allow-Origin' '*';
```

**Comment by mchulet** [comment] 2017-02-20 03:49
@erankor Thanks for your response.

I added these headers but it does not function. I don't a connection being made to the nginx server in Chrome Developer console.

Please see this link for my conf file: https://www.dropbox.com/s/0o895fbyxxl0spk/nginx.conf?dl=0

Here is what I see on the browser: https://www.dropbox.com/s/iezkw04qgouy3f4/2017-02-20_9-18-31.png?dl=0

Your help is much appreciated.

-Thanks

**Comment by mchulet** [comment] 2017-02-20 03:56
I tried putting videojs files also on the same server that has nginx but even then the same error comes up in browser console:

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media

**Comment by mchulet** [comment] 2017-02-20 04:07
@erankor Also can you please help me understand the kind of performance I can expect from this hls system on Raspberry Pi Model B which has 1GHz CPU & 1GB RAM ? I have tried other streamers like Nimble but it would start stuttering even with 5 connections from mobile phones.

**Comment by erankor** [comment] 2017-02-20 07:07
You should not have these 'add_header's more than once, have it in one of the blocks but not both. But that is probably not the problem, as you would get a different error in such a case. Can you send a URL to the stream?
I have never ran this module on such a weak environment, so I don't have any numbers. But I can say that in general, the module was developed with a strong focus on performance. If you apply the performance recommendations in the readme, you will probably get good enough performance on your environment as well. 
Only thing that may be problematic in your env is the amount of memory, if you have long videos their metadata (moov atom) can be large (I've seen extreme cases in which it was 100-200MB) and the whole metadata have to reside in memory in order to process a request (preferably the metadata should also be cached to avoid reading it for each segment)

**Comment by mchulet** [comment] 2017-02-21 07:42
@erankor I am able to play http://192.168.1.3/content/test.mp4/index.m3u8 using https://github.com/dailymotion/hls.js but somehow videojs is not playing it. Trying to resolve whats stopping videojs from playing this content.

**Comment by erankor** [comment] 2017-02-21 12:55
Ok, but I meant an external URL... so that I could use it to reproduce the issue

**Comment by mchulet** [comment] 2017-02-21 14:42
Its on device right now, let me set it up for external IP. What could be possible reasons for it playing on dailymotion hls javascript library but not on videojs ?

**Comment by erankor** [comment] 2017-02-21 15:51
I'm not familiar enough with the internals of these players to answer that. In general, when it comes to hls, my view is that if it plays on Safari, the stream is ok. However, non-Apple players may be less resilient and fail to play it, e.g. they may not handle segments that do not start with a keyframe.

**Comment by mchulet** [comment] 2017-02-21 18:15
My current observation of dailymotion hls javascript library has been on Windows/Chrome. My target devices are Android/iOS phones. Will test on them and update on the results observed.

Is there any other approach to follow to ensure that the stream works everywhere ? would it require hls & mpeg-dash combination ? I was earlier trying with RTMP module for nginx(https://github.com/arut/nginx-rtmp-module) but found that it requires ffmpeg/fprobe scripting to generate stream with proper start keyframe. Does nginx-vod-module ensure proper keyframe at start ?

-Thanks

**Comment by erankor** [comment] 2017-02-28 10:13
Just noticed I missed this thread - nginx-vod-module does not perform video transcoding, so it has no control over keyframe positions. What it does offer is the ability to push the segment boundaries to the next keyframe position (vod_align_segments_to_key_frames), this can help if the key frame positions are roughly ok, but not 100%.
The set of required protocols depend on your target devices and the players you use. For example, if you want to support old browsers that don't have MSE support, you will probably need to use some flash player. You can use flashls there, and continue hls, but the "native" format for flash is hds, so hds may work better.
Another example is if you need to support old browsers and DRM, you may need MSS in this case.

**Comment by erankor** [comment] 2017-03-14 21:05
@mchulet, can we close this issue?

**Comment by mchulet** [comment] 2017-03-15 05:19
@erankor Thanks for the info you provided. Please close this issue.

**Closed** 2017-03-15 05:49 UTC
