### ISSUE TITLE
Duplicated subtitles

### ISSUE THREAD

**Issue by lucasdavila86** [kaltura/nginx-vod-module#560] opened 2017-03-16 23:10 UTC
Hi,

We found that the subtitles are appearing duplicated when they are chunked n multiple vtt files.
We are using the Feb 7 commit (60477e9dd7c5f21eb5d12f2e0fafcbef9c76a25d) and nginx 1.11.9
For example, 
getting the seg-9-f1.vtt
```
WEBVTT

1
00:01:27.066 --> 00:01:31.100
Dos familias, de igual dignidad,
```
And getting seg-10-f1.vtt
```
WEBVTT

1
00:01:27.066 --> 00:01:31.100
Dos familias, de igual dignidad,

2
00:01:31.100 --> 00:01:35.033
en la hermosa Verona,
donde colocamos nuestra escena,
```
In this case the player shows up two times the first line.
This is happening on all the transitions between segments.

I can provide you a link to test it out
https://teatrix.rocstar.tv/test/rcs/subs/lang/,spa/romeojuliet_es.srt,eng/romeojuliet_600k.mp4,.urlset/master.m3u8

Thanks in advance,
Lucas

**Comment by erankor** [comment] 2017-03-17 04:37
When the start/end time of a caption line spans over multiple segments, it should appear in both, it's not a bug.
Here is a sample from Apple - master manifest: https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8
`
curl https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/subtitles/eng/fileSequence0.webvtt | tail
line:25%

00:00:27.000 --> 00:00:29.000 line:50%
English subtitle 14 -Unforced- (00:00:27.000)
line:50%

00:00:29.000 --> 00:00:31.000 line:75%
English subtitle 15 -Forced- (00:00:27.000)
line:75%
`
`
curl https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_16x9/subtitles/eng/fileSequence1.webvtt | head
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

00:00:29.000 --> 00:00:31.000 line:75%
English subtitle 15 -Forced- (00:00:27.000)
line:75%

00:00:31.000 --> 00:00:33.000 align:start line:0%
English subtitle 16 -Unforced- (00:00:31.000)
align:start line:0%
`

Which player are you using? did you try Safari's native player on iPhone?

**Comment by lucasdavila86** [comment] 2017-03-17 16:00
We are using JWplayer.
I've just tried it with the safari player on IPhone and the subtitles doesn't appears duplicated.
Sorry for the inconvenience
Thanks!

**Comment by erankor** [comment] 2017-03-17 20:37
Thanks for the update, closing.

**Closed by erankor** 2017-03-17 20:37 UTC

**Comment by flavioribeiro** [comment] 2017-05-11 16:38
heads up on this that [hlsjs#v0.7.7](https://github.com/video-dev/hls.js/releases/tag/v0.7.7) fixes the problem of showing duplicated captions on client side.
