### ISSUE TITLE
Testing custom hook 

### ISSUE THREAD

**Issue by jessport1** [kaltura/nginx-vod-module#105] opened 2015-06-14 08:57 UTC
Please disregard.

**Comment by kaltura-hooks** [comment] 2015-06-14 10:33
Hi @jessport1,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please
ensure that your issue includes the following (please comment with more info if you have not included all this info in
your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Is Nginx installed from the kaltura-nginx RPM or deb package?
	When using RPM, paste the output for:
```
	# rpm -qa kaltura-nginx
```	
	For deb based systems:
```	
	# dpkg -l kaltura-nginx
```
 - If the issue is with the install process, please provide full output of the apt-get/yum install command.
 - If you compiled Nginx on your own, please provide the output for:
	```
	$ uname -a
	$ gcc -v
	```
	If using a compiler other than GCC, please provide exact name and version.
	Also, provide the configure line you used.
- Check Nginx error logs and provide relevant output

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Closed** 2015-06-14 10:41 UTC
