### ISSUE TITLE
upstream buffer is too small to read response

### ISSUE THREAD

**Issue by arty777** [kaltura/nginx-vod-module#294] opened 2016-05-04 08:38 UTC
Hi , it's happens when try to vod  file  . How to fix? I use remote config

2016/05/04 11:22:37 [alert] 587#587: *71 upstream buffer is too small to read response while reading response header from upstream, client: *.*.*.*, server: example.com, request: "GET /view/133089.mp4/seg-2-v1-a1.ts HTTP/1.0", subrequest: "/backend/view/133089.mp4", upstream: "http://127.0.0.1/view/
test.mp4", host: "example.com", referrer: "http://192.168.88.2:8080/my/test_hls.html"

**Comment by erankor** [comment] 2016-05-04 08:50
Any chance the upstream server returns very large headers ? (you can check it with curl -i)
If so, you can increase the value of vod_max_upstream_headers_size (the default value is 4k)

**Comment by arty777** [comment] 2016-05-04 09:04
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 04 May 2016 09:06:23 GMT
Content-Type: video/MP2T
Content-Length: 349304

**Comment by erankor** [comment] 2016-05-04 09:05
These headers show content-type = mpeg ts, I was referring to the server that serves the mp4

**Comment by arty777** [comment] 2016-05-04 09:17
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 04 May 2016 09:18:38 GMT
Content-Type: video/mp4
Content-Length: 128707884
Last-Modified: Tue, 04 Aug 2015 16:44:00 GMT
Connection: close
ETag: "55c0ebd0-7abed2c"
Accept-Ranges: bytes

**Comment by erankor** [comment] 2016-05-04 10:12
The size should not matter, it does not download the whole file, maybe the remote server does not accept range requests ? (even though the header says it does...)
Can you send me the address of this server so that I can check it out ?

**Comment by arty777** [comment] 2016-05-04 11:09
example
http://test.china-cdn88nmbwacdnln8hq8qwe.com/view/133089.mp4/master.m3u8

**Comment by erankor** [comment] 2016-05-04 12:22
I meant the server that serves the mp4 file, I want to reproduce the error in my server.
Also, I didn't see the error in the m3u8 URL you sent - downloaded the index.m3u8 and a couple of segments and they worked.

**Comment by arty777** [comment] 2016-05-04 13:00
All work fine , but time to time i see upstream buffer is too small to read response while reading response header from upstream, client

**Comment by erankor** [comment] 2016-05-04 15:06
Can capture the upstream traffic in case of error with tcpdump and send me the result ? (eran.kornblau at kaltura dot com)
Also,are you using localhost as the upstream just for testing or something ? because it doesn't really make sense for real use, you'd better off just use local mode instead, will work faster..

**Comment by arty777** [comment] 2016-05-05 09:19
>Also,are you using localhost as the upstream just for testing or something ? because it doesn't really >make sense for real use, you'd better off just use local mode instead, will work faster..

try_files does.t work with local mode (( Only remote work fine for my configuration

**Comment by erankor** [comment] 2016-05-05 09:55
Ok, although I believe using nginx's if with local mode is expected to be more efficient in this case than remote mode

**Comment by arty777** [comment] 2016-05-05 10:07
I do not against working in local mode, but how to be in such a case, if the MP4 files are scattered in a large Number of hard drives?
I use try_files for this case

**Comment by erankor** [comment] 2016-05-05 11:21
I was referring to the solution I proposed in this thread https://github.com/kaltura/nginx-vod-module/issues/143.Naturally, if you have dozens of paths to try it won't be too convenient, but if that is really the case, I think it makes more sense to save the mapping of video id => path in some database, and work in mapped mode (that's what we do). Because even with try files, nginx has to check for the location of the file in each of the volumes until it finds it

**Comment by arty777** [comment] 2016-05-05 11:33
I store the path to the files in the database, the absolute path to the file, and nginiks already takes a direct path, without unnecessary seek drives

perl_set $dice 'sub {
use DBI;

    my $r    = shift;
    my $root = $r->variable("document_root");
    my $filename = $r->filename;
    $filename=~ s/^.*\///;
    $db_host="localhost";
    $db_name ="nginx_tools_DB";
    $db_user = "example";
    $db_pass = "my_test_password";
    $query = "SELECT f_get_file_path(\'$filename\')";
    $drh = DBI->install_driver("mysql");
    $dsn = "DBI:mysql:database=$db_name;host=$db_host";
    $dbh = DBI->connect($dsn,$db_user,$db_pass);
    my $sth = $dbh->prepare($query);
    $sth->execute();
    my @ref = $sth->fetchrow_array();
    $sth->finish();
    $dbh->disconnect();
    my $string="$ref[0]";
    $string =~ s/$root//;
    return "$string";
}';

...........


location /video/ {
....
        root /files;

try_files $dice
=404;

...........



  Talk more detail about map mode , how to " save the mapping of video id => path in some database, and work in mapped mode "

**Comment by erankor** [comment] 2016-05-05 13:54
In its simplest form, mapped mode makes nginx vod perform an HTTP request to some server, get back a JSON that contains the file path, and proceed to stream the file as it does in local mode.
The JSON can also contain more complex structures like playlists etc. it's described here https://github.com/kaltura/nginx-vod-module/#mapping-response-format. 
To just map the request to a single MP4 you need to return a JSON in this format https://github.com/kaltura/nginx-vod-module/#simple-mapping

**Comment by erankor** [comment] 2016-05-08 12:10
Following our email correspondence, this issue should be resolved by https://github.com/kaltura/nginx-vod-module/pull/301.
Please confirm

**Comment by arty777** [comment] 2016-05-08 19:35
Nice, issue gone , thank you .

**Comment by erankor** [comment] 2016-05-09 07:26
Great, thanks for confirming

**Closed by erankor** 2016-05-09 07:26 UTC
