### ISSUE TITLE
Trouble understanding what to do after installing.

### ISSUE THREAD

**Issue by jackiboy** [kaltura/nginx-vod-module#738] opened 2017-11-22 07:12 UTC
Hi.
I have installed the `kaltura-nginx` package, everything seems to be setup and running, just wondering what I need to do next? I assume it is setup in mapped configuration by looking at the `kaltura.conf` file.

If so where do I create the JSON files for Nginx to read (I want to setup streams to be served with HLS), what do I name the JSON files?

Cheers,
Jack

**Comment by erankor** [comment] 2017-11-22 07:40
The default configuration that comes with the package indeed uses mapped mode, since it's built to work with the Kaltura platform. The JSON files are fetched from an upstream server, whose address is set here - https://github.com/kaltura/nginx-vod-module/blob/master/conf/nginx.conf.template#L16.
If you don't use the Kaltura platform, and you don't need advanced features (such as playlist) you can simply switch to local mode, and add location like this:
```
		location /hls/ {
			vod hls;
			alias /mp4/files/root/;
		}
```
With this location, a request for `/hls/video.mp4/master.m3u8` will look for a file called `/mp4/files/root/video.mp4`

**Comment by jackiboy** [comment] 2017-11-22 08:38
@erankor thanks mate! I ended up building it from source, and now have  a stream working. With Local Mode can I use a video that has 2 or 3 audio tracks? 

Also it is very slow when first grabbing the stream. I assume this is my low powered test server (1GB Ram 1 CPU) ?

**Comment by erankor** [comment] 2017-11-22 08:44
Are you asking about alternative audio tracks (e.g. different languages)? If so, then it will work fine with local mode, if the tracks are appropriately tagged in the mp4 file.
Regarding speed, if you are getting a slow response when you curl localhost, the problem is most likely with the storage on which the mp4s reside.

**Comment by jackiboy** [comment] 2017-11-23 20:48
@erankor yup working great :-) unsure why it was slow. I rebuilt the server from scratch and it is working a lot better now. Where are the m3u8 files stored/cached?

**Comment by erankor** [comment] 2017-11-23 20:58
If you enable vod_response_cache, the manifests will be cached in shared memory. If you don't, they won't be cached, and will be rebuilt from scratch on every request.

**Comment by jackiboy** [comment] 2017-11-23 21:01
Yup I have that enabled.
```
        vod_metadata_cache metadata_cache 512m;
        vod_response_cache response_cache 128m;

```
I am serving over https (SSL & http2) will it still serve from the cache if so?

**Comment by erankor** [comment] 2017-11-23 21:04
Actually, I never tested with http2, but yes, it should return from cache, it's not related to the underlying transport. You can enable the performance counters + status page, and check the cache hit/miss ratio.

**Comment by jackiboy** [comment] 2017-11-23 21:12
How do I do that?

`vod_performance_counters on;`

what do I need to do here?
https://github.com/kaltura/nginx-vod-module#vod_status

**Comment by erankor** [comment] 2017-11-24 05:25
yes, you need `vod_performance_counters on`, and you need to put vod_status on some location, e.g. 
```
location = /vod_status {
	vod_status;
	allow 192.168.0.0/16;
	deny all;
}
```
after you do that, you can curl your-server/vod_status to get the status XML

**Comment by erankor** [comment] 2017-12-03 12:06
@jackiboy, can we close this issue?

**Comment by jackiboy** [comment] 2017-12-03 13:16
@erankor sure thing! Thanks for your help.

**Closed** 2017-12-03 15:24 UTC
