### ISSUE TITLE
invalid value "thumb" in "vod" directive

### ISSUE THREAD

**Issue by anhngodangquoc** [kaltura/nginx-vod-module#498] opened 2016-12-22 07:18 UTC
I install kaltura-nginx and kaltura ffmpeg  by yum already. lasttime it work ok, i can get thumb from video. But today, i try to restart kaltura-nginx and i got:

nginx: [emerg] invalid value "thumb" in "vod" directive, it must be one of: none,dash,hds,hls,mss

what can i do now?

kaltura-nginx-1.10.2-4.x86_64
kaltura-ffmpeg-3.2-1.x86_64

**Comment by ahotnik** [comment] 2016-12-22 07:25
Hello, i'm sorry for my message in this  @issue. Can you explain me how to use kaltura? 
My email vlad-ua95@yandex.ru
My regards and sorry..

**Comment by erankor** [comment] 2016-12-27 20:21
This was caused by a change in ffmpeg API (the functions used for thumbnail grabbing became deprecated in the latest ffmpeg). We've just finished updating the code to work against the new API, a new package will be available on Sunday.

**Comment by jessp01** [comment] 2016-12-28 18:05
Hello @anhngodangquoc,

Like @erankor wrote, the next stable release will include kaltura-nginx compiled against ffmpeg 3.2 and will be released on Sun.
However, you can already obtain the new version from the nightly repo. 
For RHEL/CentOS 6 use:
```
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.origin.kaltura.org/releases/nightly/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1
```

For RHEL/CentOS 7 use:
```
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.origin.kaltura.org/releases/rhel7/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1
```

**Comment by jessp01** [comment] 2017-01-10 16:58
The stable repo now contains kaltura-nginx packages compiled with the latest vod module tag [1.12] and ffmpeg 3.2 so both vod features that require ffmpeg should now work correctly.

**Closed by jessp01** 2017-01-10 16:58 UTC

**Comment by RecareLee** [comment] 2017-05-04 07:08
Hi, @jessp01 
    My linux operate system is SUSE . How should i compile my nginx (add nginx vod mudule) to support thumbnail capture function？

**Comment by jessp01** [comment] 2017-05-04 11:20
Hi @RecareLee,

We only ship packages for RHEL/CentOS and Debian/Ubuntu. SLES also uses the RPM format for packaging however, it often has different package names and file paths and so, trying to install the RPM packages meant for RHEL/CentOS has the potential to fail.

You can compile the Nginx VOD module from source. In order to make use of the thumbnail capture, you need to have FFmpeg 3.2 on your machine, both the shared objects and the header files are needed.
If you use Nginx >= 1.9.11, you can compile the VOD module as a DSO, if you're using an older Nginx version, you will need to compile it statically into the Nginx binary.
This is explained here:
https://github.com/kaltura/nginx-vod-module#build

If your FFmpeg is not installed onto a path the compiler, linker and dynamic loader look at by default, you'll need to export the following ENV vars to include the paths, like so:
```
LD_LIBRARY_PATH=$FFMPEG_BASEDIR/lib
LIBRARY_PATH=$FFMPEG_BASEDIR/lib
C_INCLUDE_PATH=$FFMPEG_BASEDIR/include
```

**Comment by RecareLee** [comment] 2017-05-05 07:23
Thanks @jessp01 , i just have already get the ffmpeg-master source code in my linux environment. the ffmpeg source code's directory are: 

libavcodec
libavdevice
libavfilter
libavformat
libavresample
libavutil
libpostproc
library.mak
libswresample
libswscale
presets
tests
tools
version.sh

how should i configure the ENV vars?

**Comment by jessp01** [comment] 2017-05-06 20:52
Hi @RecareLee,

Having the FFmpeg source is not enough, you need to compile it.
If you run ffmpeg's configure command without --prefix, the prefix will be /usr/local.
Once compiled, you need to set ENV vars as I wrote before:
```
LD_LIBRARY_PATH=$FFMPEG_PREFIX/lib
LIBRARY_PATH=$FFMPEG_PREFIX/lib
C_INCLUDE_PATH=$FFMPEG_PREFIX/include
```

**Comment by RecareLee** [comment] 2017-05-08 01:58
Sorry, @jessp01 , i compiled ffmpeg without --prefix, there were some ffmpeg's  '.a' files on the path  /usr/local/lib, however it still failed when configured thumb directive..

# ls /usr/local/lib/libav*
 /usr/local/lib/libavcodec.a 
 /usr/local/lib/libavdevice.a 
 /usr/local/lib/libavfilter.a 
 /usr/local/lib/libavformat.a 
 /usr/local/lib/libavutil.a

**Comment by jessp01** [comment] 2017-05-08 16:12
Hi @RecareLee,

This feature requires libavcodec, which according to your output, you've got the archive file for, though I recommend you link against the SO and not the archive [dynamic linkage vs. static].

If you installed FFmpeg onto /usr/local, the ENV vars should be exported like so:
```
LD_LIBRARY_PATH=/usr/local/lib
LIBRARY_PATH=/usr/local/lib
C_INCLUDE_PATH=/usr/local/include
```

At any rate, the tests to determine whether the lib is available are done here: https://github.com/kaltura/nginx-vod-module/blob/master/config#L60

I suggest you take a look at the configure output and also at objs/autoconf.err to see why libavcodec is not found.

**Comment by RecareLee** [comment] 2017-05-09 02:39
Hi,@jessp01 
    The output when  i try to configure ffmpeg to /usr/local is as following:

License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...
config.h is unchanged
config.asm is unchanged
libavutil/avconfig.h is unchanged
libavcodec/bsf_list.c is unchanged
libavformat/protocol_list.c is unchanged
