### ISSUE TITLE
Proper response codes

### ISSUE THREAD

**Issue by meteozond** [kaltura/nginx-vod-module#404] opened 2016-08-22 13:16 UTC
We are building content delivery network, where our clients will be able to get video streaming features with this great `nginx-vod-module`. The problem is that if our user uploaded wrong file we are not able to process this situation consistently, because we are getting 404 status code on any exceptional case what is not actually true. Because file exists and problem is that nginx can't parse it or etc. And the only way to clarify this problem is to dig into the log file.

In our opinion module should return proper status codes (e.g. 5xx) for each case, because it failed during file procession and have to provide enough information.

**Comment by erankor** [comment] 2016-08-22 15:49
the mapping of errors to http statuses can be found here:
https://github.com/kaltura/nginx-vod-module/blob/master/ngx_http_vod_utils.c#L3

but the problem is that there is no http status that accurately describes the condition of an invalid media type. I was thinking about using 415 since it sounds like it (unsupported media type) but that's not what it's meant for either.

**Comment by meteozond** [comment] 2016-08-24 07:35
Agree 415 sounds good at first glance, but I think 400 is better for this case, at least it is more convenient than 404.

**Comment by erankor** [comment] 2016-08-24 08:07
Yeah, but then we have the same error code for invalid request and corrupt file which is not ideal either.
A better approach may be to expose the error string or at least the internal error code (which I linked to above) as an nginx variable. This will enable you to return it as a response header, so that you'll have for example HTTP status 404, but with `X-Vod-Error: bad file data`.
I don't have the time to handle it now, but will add it to the todo...

**Comment by erankor** [comment] 2016-11-23 14:29
Merged this solution here - https://github.com/kaltura/nginx-vod-module/pull/464
It does not cover 100% of the cases, but for most errors `$vod_status` can be used to get a more detailed error reason than the HTTP status.

**Closed** 2016-11-27 08:44 UTC
