### ISSUE TITLE
Failed to fetch during installation

### ISSUE THREAD

**Issue by odinotisan** [kaltura/nginx-vod-module#1151] opened 2020-06-17 19:56 UTC
During installation, on both centos/ubuntu.

`E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-ffmpeg/kaltura-ffmpeg_4.0.2-3_amd64.deb  404`
`E: Failed to fetch http://installrepo.kaltura.org/repo/apt/xenial/pool/main/k/kaltura-nginx/kaltura-nginx_1.17.10-1_amd64.deb  404`

**Comment by skhalymon** [comment] 2020-06-17 21:18
Same issue here...

**Comment by jessp01** [comment] 2020-06-18 07:46
Hi all,

Please see https://github.com/kaltura/nginx-vod-module/issues/892#issuecomment-413271054

Thanks,

**Comment by jessp01** [comment] 2020-06-21 15:00
Hi all,

Can you please confirm the issue is resolved and, if so, close it?
Thanks,

**Comment by jessp01** [comment] 2020-06-26 15:20
Closing due to lack of response. Feel free to reopen if there's still an issue.
Thanks,

**Closed by jessp01** 2020-06-26 15:20 UTC

**Comment by odinotisan** [comment] 2020-06-28 13:19
Confirmed. It's working right now.
