### ISSUE TITLE
Remote explanation

### ISSUE THREAD

**Issue by shaharmor** [kaltura/nginx-vod-module#106] opened 2015-06-15 15:33 UTC
Hi,

What i'm trying to do is have the nginx accept a request in the format like:
http://mynimbleserver.com/remote/http://anotherserver.com/video.mp4/master.playlist

and that the nginx will fetch the remote mp4 and transmux it to HLS on the fly, without me having to manually copy the video.mp4 file to the server or something of that sort.

Is that possible?

**Comment by kaltura-hooks** [comment] 2015-06-15 16:03
Hi @shaharmor,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Is Nginx installed from the kaltura-nginx RPM or deb package?
	When using RPM, paste the output for:
```
	# rpm -qa kaltura-nginx
```	
	For deb based systems:
```	
	# dpkg -l kaltura-nginx
```
 - If the issue is with the install process, please provide full output of the apt-get/yum install command.
 - If you compiled Nginx on your own, please provide the output for:
	```
	$ uname -a

	$ gcc -v
	```
	If using a compiler other than GCC, please provide exact name and version.
	Also, provide the configure line you used.
 - Check Nginx error logs and provide relevant output

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by erankor** [comment] 2015-06-15 20:17
Yes, remote mode supports pulling the required parts of the file using HTTP range requests and repackaging to HLS/HDS... However it does not currently support having the remote domain dynamic, don't know if that's what you meant.
If the remote domain is fixed, then for your sample URL, you'd need to create an 'upstream' in your nginx.conf to 'http://anotherserver.com' and point the nginx-vod-module to this upstream using the vod_upstream command. 
The URL:
http://mynimbleserver.com/remote/video.mp4/master.m3u8
Would pull the file http://anotherserver.com/remote/video.mp4 and repackage it to HLS.
Take a look at this sample config: https://github.com/kaltura/nginx-vod-module/#remote-configuration
and also at https://github.com/kaltura/nginx-vod-module/#url-structure

**Comment by shaharmor** [comment] 2015-06-16 06:46
Hey Eran,

I don't mind configuring the domain manually in the nginx.conf.
Actually i've tried what you said but i just can't seem to get it to work.

This is the location i added to nginx:

```
# server remote MP4 as HLS
                location ~ ^/remote/p/\d+/(sp/\d+/)?serveFlavor/ {
                        vod hls;
                        vod_mode remote;
                        vod_moov_cache moov_cache 512m;
                        vod_secret_key mukkaukk;
                        vod_child_request_path /__child_request__/;
                        vod_upstream remoteupstream;
                        vod_upstream_host_header kaltura.peer5.com;

                        gzip on;
                        gzip_types application/vnd.apple.mpegurl;

                        expires 100d;
                        add_header Last-Modified "Sun, 19 Nov 2000 08:52:00 GMT";
                }
```

and this is the upstream:
```
upstream remoteupstream {
                server www.mp4server.com;
        }
```

Now i don't understand the URL structure i need to use.

From my understanding it should be something like:
http://myserver.com/remote/p/123/PATH_TO_MP4_ON_UPSTREAM/master.m3u8

but that only gets me a 404 page...

**Comment by erankor** [comment] 2015-06-16 06:50
this configuration assumes Kaltura URL structure - /p/123/serveFlavor/...
if your 'PATH_TO_MP4_ON_UPSTREAM' does not start with serveFlavor it will return 404.
If you don't use Kaltura URL structure you should probably just use location /remote/ (without regular expressions)
If that still doesn't work, please check your nginx error log for any messages

**Comment by shaharmor** [comment] 2015-06-16 07:00
This is the error i see in the log:

```
2015/06/16 06:57:12 [error] 20669#0: *9 ngx_http_vod_process_header: upstream returned a bad status 404 while reading response header from upstream, client: x.x.x.x, server: mynimbleserver.com, request: "GET /remote/PATH_TO_MP4.mp4/master.m3u8 HTTP/1.1", subrequest: "/__child_request__//remote/PATH_TO_MP4.mp4", upstream: "kalapi://y.y.y.y:80", host: "mynimbleserver.com:88"
```

But again nothing shows up :(

I change the location to have only `/remote/` in the url, so the mp4server must start with /remote/ as well?

**Comment by erankor** [comment] 2015-06-16 07:05
this error means that http://www.mp4server.com/remote/PATH_TO_MP4.mp4 returned 404, you need to fix it so that it will return the mp4 file

**Comment by shaharmor** [comment] 2015-06-16 07:27
Working now! thanks a lot!

One last question, for the remote thingy to work i don't need an entire Kaltura server right? just the nginx-vod-module is enough?

**Comment by erankor** [comment] 2015-06-16 07:44
yes, you don't need Kaltura server

**Closed by erankor** 2015-06-16 07:44 UTC
